#
# arch/ubicom32/mach-ip8k/Makefile
#	Makefile for ip8k based boards.
#
# (C) Copyright 2009, Ubicom, Inc.
#
# This file is part of the Ubicom32 Linux Kernel Port.
#
# The Ubicom32 Linux Kernel Port is free software: you can redistribute
# it and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 2 of the
# License, or (at your option) any later version.
#
# The Ubicom32 Linux Kernel Port is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
# the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the Ubicom32 Linux Kernel Port.  If not, 
# see <http://www.gnu.org/licenses/>.
#
# Ubicom32 implementation derived from (with many thanks):
#   arch/m68knommu
#   arch/blackfin
#   arch/parisc
#

obj-$(CONFIG_IP8000QEMU)	+= board-ip8000qemu.o
obj-$(CONFIG_IP8000BRINGUP)	+= board-ip8000bringup.o
obj-$(CONFIG_IP8100RGW_ES)	+= board-ip8100rgw.o
obj-$(CONFIG_IP8100RGW)		+= board-ip8100rgw.o
obj-$(CONFIG_IP8500TAP)		+= board-ip8500tap.o
obj-$(CONFIG_IP8500TAP_ES)	+= board-ip8500tap.o
obj-$(CONFIG_IP8500TAP_DAO)	+= board-ip8500tap.o
