/* ubicom32 ELF support for BFD.
   Copyright (C) 2000 Free Software Foundation, Inc.

This file is part of BFD, the Binary File Descriptor library.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software Foundation, Inc.,
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */

#ifndef _ELF_UBICOM32_H
#define _ELF_UBICOM32_H

#include "elf/reloc-macros.h"

/* Relocations.  */
START_RELOC_NUMBERS (elf_ubicom32_reloc_type)
  RELOC_NUMBER (R_UBICOM32_NONE, 0)
  RELOC_NUMBER (R_UBICOM32_16, 1)
  RELOC_NUMBER (R_UBICOM32_32, 2)
  RELOC_NUMBER (R_UBICOM32_LO16, 3)
  RELOC_NUMBER (R_UBICOM32_HI16, 4)
  RELOC_NUMBER (R_UBICOM32_21_PCREL, 5)
  RELOC_NUMBER (R_UBICOM32_24_PCREL, 6)
  RELOC_NUMBER (R_UBICOM32_HI24, 7)
  RELOC_NUMBER (R_UBICOM32_LO7_S, 8)
  RELOC_NUMBER (R_UBICOM32_LO7_2_S, 9)
  RELOC_NUMBER (R_UBICOM32_LO7_4_S, 10)
  RELOC_NUMBER (R_UBICOM32_LO7_D, 11)
  RELOC_NUMBER (R_UBICOM32_LO7_2_D, 12)
  RELOC_NUMBER (R_UBICOM32_LO7_4_D, 13)
  RELOC_NUMBER (R_UBICOM32_32_HARVARD, 14)
  RELOC_NUMBER (R_UBICOM32_LO7_CALLI, 15)
  RELOC_NUMBER (R_UBICOM32_LO16_CALLI, 16)
  RELOC_NUMBER (R_UBICOM32_GOT_HI24, 17)
  RELOC_NUMBER (R_UBICOM32_GOT_LO7_S, 18)
  RELOC_NUMBER (R_UBICOM32_GOT_LO7_2_S, 19)
  RELOC_NUMBER (R_UBICOM32_GOT_LO7_4_S, 20)
  RELOC_NUMBER (R_UBICOM32_GOT_LO7_D, 21)
  RELOC_NUMBER (R_UBICOM32_GOT_LO7_2_D, 22)
  RELOC_NUMBER (R_UBICOM32_GOT_LO7_4_D, 23)
  RELOC_NUMBER (R_UBICOM32_FUNCDESC_GOT_HI24, 24)
  RELOC_NUMBER (R_UBICOM32_FUNCDESC_GOT_LO7_S, 25)
  RELOC_NUMBER (R_UBICOM32_FUNCDESC_GOT_LO7_2_S, 26)
  RELOC_NUMBER (R_UBICOM32_FUNCDESC_GOT_LO7_4_S, 27)
  RELOC_NUMBER (R_UBICOM32_FUNCDESC_GOT_LO7_D, 28)
  RELOC_NUMBER (R_UBICOM32_FUNCDESC_GOT_LO7_2_D, 29)
  RELOC_NUMBER (R_UBICOM32_FUNCDESC_GOT_LO7_4_D, 30)
  RELOC_NUMBER (R_UBICOM32_GOT_LO7_CALLI, 31)
  RELOC_NUMBER (R_UBICOM32_FUNCDESC_GOT_LO7_CALLI, 32)
  RELOC_NUMBER (R_UBICOM32_FUNCDESC_VALUE, 33)
  RELOC_NUMBER (R_UBICOM32_FUNCDESC, 34)
  RELOC_NUMBER (R_UBICOM32_GOT_LO, 35)
  RELOC_NUMBER (R_UBICOM32_GOT_HI, 36)
  RELOC_NUMBER (R_UBICOM32_FUNCDESC_GOT_LO, 37)
  RELOC_NUMBER (R_UBICOM32_FUNCDESC_GOT_HI, 38)
  RELOC_NUMBER (R_UBICOM32_LO7_LEAI, 39)
  RELOC_NUMBER (R_UBICOM32_LO16_LEAI, 40)
  RELOC_NUMBER (R_UBICOM32_GOT_LO_LEAI, 41)
  RELOC_NUMBER (R_UBICOM32_FUNCDESC_GOT_LO_LEAI, 42)
  RELOC_NUMBER (R_UBICOM32_GNU_VTINHERIT, 200)
  RELOC_NUMBER (R_UBICOM32_GNU_VTENTRY, 201)
END_RELOC_NUMBERS(R_UBICOM32_max)


/*
 * Processor specific flags for the ELF header e_flags field.
 */
#define EF_UBICOM32_PIC         0x80000000      /* -fpic */
#define EF_UBICOM32_FDPIC       0x40000000      /* -mfdpic */

#define EF_UBICOM32_PIC_FLAGS   (EF_UBICOM32_PIC | EF_UBICOM32_FDPIC)

#endif /* _ELF_IP_H */
