#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by git-commit with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git-rev-parse --verify HEAD 2>/dev/null
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi


if ! git diff --cached -- | scripts/checkpatch.pl -q --pre-commit - > pre_commit_errors; then
    echo "ERROR: Pre-commit checkpatch failed." >&2;
    cat pre_commit_errors >&2;
    echo "Please Correct these errors and add them to the index before commiting." >&2;
    exit 1;
fi
