/* calc.h.  Generated by configure.  */
/* calc.h.in.  Generated automatically from configure.in by autoheader.  */

/* Define if you have the <stdlib.h> header file.  */
#define HAVE_STDLIB_H 1

/* Name of package */
#define PACKAGE "calc"

/* Version number of package */
#define VERSION "1.1"

