#!/bin/sh
# Copyright (C) 2009-2010 OpenWrt.org
# Copyright (C) 2010 Vertical Communications
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

blkdev=`dirname $DEVPATH`
if [ `basename $blkdev` != "block" ]; then

    case "$ACTION" in
	add)
		/etc/init.d/minidlna restart
		;;
	remove)
		/etc/init.d/minidlna stop
		;;
    esac	

fi

