# Makefile for uClibc
#
# Copyright (C) 2000-2006 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

CSRC := syscall.c __syscall_error.c

ifeq ($(ARCH_USE_MMU),y)
      CSRC += brk.c
endif

 
SSRC := clone.S setjmp.S vfork.S

include $(top_srcdir)libc/sysdeps/linux/Makefile.commonarch
